/* PARTNER */
export const GET_PARTNER = "GET_PARTNER"
export const GET_PARTNER_SUCCESS = "GET_PARTNER_SUCCESS"
export const GET_PARTNER_FAIL = "GET_PARTNER_FAIL"
export const PROCCESSING_REQUEST = "PROCCESSING_REQUEST"